<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace plagiarism_docguard;

defined('MOODLE_INTERNAL') || die();

/**
 * Authenticity findings: things present in a submission that should not be there, and
 * references in it that cannot be verified.
 *
 * WHAT THIS CLASS DELIBERATELY DOES NOT DO
 *
 * It does not measure how the writing reads. No sentence lengths, no vocabulary richness, no
 * marker words, no "this sounds like AI". Every one of those was measured and failed:
 *
 *  - The marker-word signals shipped to 1.0.98 flagged 0 of 48 answers generated by ChatGPT,
 *    Gemini and Claude, and found zero markers in 48 of 48. The highest-scoring document in
 *    that exercise was a human student writing in their second language.
 *  - Style statistics as absolute measures do not separate the classes: of eight measures
 *    tested, overlap between the human and AI ranges ran from 25% to 100%, and the single
 *    best one rested on a human baseline of eight documents, which is far too few to
 *    establish a range.
 *  - Comparing windows WITHIN one document - the most promising idea, because it needs no
 *    baseline - fails at assessment-answer length. Splitting 59 documents in half and
 *    comparing each author against themselves: one author's own variation between two halves
 *    of their own writing reached 36% on mean sentence length at the 90th percentile, where
 *    the median difference between two DIFFERENT authors was 20%. The same held for word
 *    length (17% vs 16%), vocabulary diversity (14% vs 8%) and long-word rate (90% vs 61%).
 *    A detector built on it flags normal writers for having written one answer in a hurry.
 *
 * So this class checks only things that are true or false about the file:
 *
 *  1. Conversational artefacts from a chat assistant, and prompt remnants. A student does not
 *     type "As an AI language model" or "Word count: 187" into an assessment.
 *  2. Markdown syntax inside a word-processed document, which indicates text composed
 *     somewhere else and pasted in.
 *  3. Legislation, standards and unit codes that do not exist. A fabricated Act section is a
 *     serious integrity finding whatever produced it.
 *  4. What the file itself records about how it was made.
 *
 * AND IT PRODUCES NO SCORE. Findings are returned individually, each with its own severity,
 * its location, and the evidence quoted verbatim. There is no composite number because there
 * is no honest way to weight these against each other yet: that requires calibration against
 * real student submissions, which this plugin has never had. A weighted total built from
 * guesses is how the previous version came to show a confident badge derived entirely from
 * signals that measured nothing.
 *
 * @package    plagiarism_docguard
 * @copyright  2026 LMS-Labs
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class authenticity {

    /**
     * @var int Version of the check set that produced a stored finding.
     *
     * Stamped on every row so that a report can say which checks ran, and so that adding or
     * removing a check later does not silently change the meaning of findings already in the
     * database. Raise it whenever a check is added, removed, or has its severity changed.
     */
    const CHECKS_VERSION = 1;

    /** @var string A finding that is decisive on its own and needs no corroboration. */
    const SEVERITY_STRONG = 'strong';


    /** @var string A finding worth a trainer's attention alongside others. */
    const SEVERITY_NOTABLE = 'notable';

    /** @var string Context only. Never sufficient to act on. */
    const SEVERITY_CONTEXT = 'context';

    /** @var int Characters of surrounding text quoted as evidence for a finding. */
    const EVIDENCE_CHARS = 180;

    /** @var int Most findings of any one kind to report, so one pathological file cannot flood a report. */
    const MAX_PER_CHECK = 12;

    /**
     * @var int Words per minute above which text was arriving in a document, not being written in it.
     *
     * Set from copy-typing speed (40-60 wpm), not composition speed (15-25), so that a learner
     * who drafted on paper and typed it up is never flagged for it. See provenance_findings().
     */
    const COMPOSITION_WPM_CEILING = 60;

    /**
     * @var int Shortest document the provenance proportionality checks apply to.
     *
     * A 40-word answer legitimately takes under a minute and records one save, so asking
     * whether its editing time is plausible is meaningless.
     */
    const PROVENANCE_MIN_WORDS = 200;

    /**
     * @var int Longest value kept from any one provenance field.
     *
     * Every provenance value comes out of a file the student uploaded, so its length is
     * theirs to choose. Uncapped, a crafted .docx carrying a 500 KB dc:creator was stored
     * verbatim - measured - and analysisjson is a TEXT column, 65,535 bytes on MySQL. One
     * upload would therefore fail the row write and lose the analysis for that submission.
     *
     * 256 characters is generous for everything real here: a person's name, an application
     * version string, an ISO timestamp, a PDF producer. Anything longer is not information,
     * and it is truncated rather than dropped so the report still shows that the field was
     * present and tampered with.
     */
    const PROVENANCE_FIELD_MAX = 256;

    /**
     * Conversational remnants from a chat assistant.
     *
     * Each entry is a case-insensitive regular expression. These are not stylistic
     * preferences, they are sentences that belong to a chat interface rather than to an
     * assessment, so a match is close to self-evident: a student would have to have typed
     * the assistant's own words into their answer.
     *
     * Kept deliberately narrow. Anything that a student might plausibly write by coincidence
     * is excluded, because a false accusation here is far more costly than a missed
     * detection. "In conclusion" is not in this list and never will be.
     *
     * @return array Map of regex => short label.
     */
    public static function assistant_artefact_patterns(): array {
        return [
            // Direct self-reference. No legitimate route into a student's assessment.
            '/\bas an? AI (?:language )?model\b/i'                 => 'AI self-reference',
            '/\bI\'?m an AI\b/i'                                   => 'AI self-reference',
            '/\bas a large language model\b/i'                     => 'AI self-reference',
            '/\bI (?:do not|don\'?t) have (?:personal )?(?:experiences|feelings|opinions)\b/i'
                                                                   => 'AI self-reference',
            '/\bI cannot browse the internet\b/i'                  => 'AI self-reference',
            '/\bmy (?:training data|knowledge cut-?off)\b/i'        => 'AI self-reference',

            // Chat framing left in place around a generated answer.
            '/\bhere(?:\'s| is) (?:a|an|your|the) (?:revised|rewritten|updated|improved|possible|sample|suggested)\b/i'
                                                                   => 'assistant framing',
            '/\bhere(?:\'s| is) (?:a|an) \d{2,4}\s*[-–to]+\s*\d{2,4}\s*word\b/i'
                                                                   => 'assistant framing',
            '/\bhere(?:\'s| is) how you (?:could|might|can) (?:answer|approach|phrase)\b/i'
                                                                   => 'assistant framing',
            '/^\s*(?:certainly|sure|absolutely|of course)[!,]\s/im' => 'assistant framing',
            '/\blet me know if you(?:\'?d| would) like\b/i'         => 'assistant framing',
            '/\bwould you like me to\b/i'                           => 'assistant framing',
            '/\bI hope this helps\b/i'                              => 'assistant framing',
            '/\bfeel free to (?:adjust|modify|tweak|personalise|personalize)\b/i'
                                                                   => 'assistant framing',
            '/\b(?:I\'?ve|I have) (?:rewritten|rephrased|simplified|expanded) (?:this|it|your)\b/i'
                                                                   => 'assistant framing',

            // The instruction, pasted in along with the answer it produced.
            '/\bword count\s*[:=]\s*\d{2,4}\b/i'                   => 'prompt remnant',
            '/\b(?:in|using|write in) (?:australian|british|american) english\b/i'
                                                                   => 'prompt remnant',
            '/\b(?:write|rewrite|make) (?:this|it) (?:sound )?(?:more )?(?:like a student|natural|simpler|less formal)\b/i'
                                                                   => 'prompt remnant',
            '/\bas if (?:written )?by a (?:student|learner)\b/i'    => 'prompt remnant',
            '/\b(?:answer|respond) in \d{2,4}\s*[-–to]+\s*\d{2,4} words\b/i'
                                                                   => 'prompt remnant',
            '/\b(?:approximately|about|around) \d{2,4} words\b/i'   => 'prompt remnant',
            '/^\s*(?:prompt|instruction)s?\s*:/im'                  => 'prompt remnant',
            '/^\s*={2,}\s*Q\s*\d+\s*={2,}\s*$/im'                   => 'prompt remnant',
        ];
    }

    /**
     * Find conversational artefacts and prompt remnants in extracted text.
     *
     * @param string $text Text as extracted from the submitted file.
     * @return array List of findings, each with check, label, severity, evidence and offset.
     */
    public static function assistant_artefacts(string $text): array {
        $findings = [];

        foreach (self::assistant_artefact_patterns() as $pattern => $label) {
            if (!preg_match_all($pattern, $text, $matches, PREG_OFFSET_CAPTURE)) {
                continue;
            }
            foreach ($matches[0] as [$matched, $offset]) {
                $findings[] = [
                    'check'    => 'assistant_artefact',
                    'label'    => $label,
                    'severity' => self::SEVERITY_STRONG,
                    'matched'  => trim($matched),
                    'offset'   => (int)$offset,
                    'evidence' => self::evidence($text, (int)$offset),
                ];
                if (count($findings) >= self::MAX_PER_CHECK) {
                    return $findings;
                }
            }
        }

        return $findings;
    }

    /**
     * Markdown syntax inside a word-processed submission.
     *
     * A Word document or PDF has its own formatting; it has no reason to contain markdown.
     * When it does, the text was composed somewhere that uses markdown - a chat interface,
     * most commonly - and pasted in.
     *
     * NOT STRONG on its own, and the reason matters: a student who drafts in a notes app, or
     * who has simply learned to type "**" for emphasis, produces the same marks. It is a
     * reason to look at how the document was assembled, not a conclusion.
     *
     * Bare hyphen bullets are excluded entirely. Plenty of people type "- " to make a list
     * and it would fire on a large share of honest submissions.
     *
     * @param string $text Text as extracted from the submitted file.
     * @return array List of findings.
     */
    public static function markdown_contamination(string $text): array {
        $patterns = [
            '/^\s{0,3}#{2,6}\s+\S/m'            => 'markdown heading',
            '/\*\*[^*\n]{2,80}\*\*/'            => 'markdown bold',
            '/(?<![\w*])\*[^*\n]{2,60}\*(?![\w*])/' => 'markdown italic',
            '/^\s{0,3}>\s+\S/m'                 => 'markdown blockquote',
            '/^\s{0,3}(?:\*|\+)\s+\S/m'         => 'markdown bullet',
            '/^\s{0,3}(?:---|___|\*\*\*)\s*$/m' => 'markdown horizontal rule',
            '/`{1,3}[^`\n]+`{1,3}/'             => 'markdown code span',
            '/\[[^\]\n]{1,80}\]\((?:https?:\/\/|www\.)[^)\s]+\)/' => 'markdown link',
        ];

        $findings = [];
        foreach ($patterns as $pattern => $label) {
            if (!preg_match_all($pattern, $text, $matches, PREG_OFFSET_CAPTURE)) {
                continue;
            }
            // One finding per KIND, carrying the count. Twelve bold spans are one
            // observation about the document, not twelve separate concerns.
            $first = $matches[0][0];
            $findings[] = [
                'check'    => 'markdown_contamination',
                'label'    => $label,
                'severity' => self::SEVERITY_NOTABLE,
                'count'    => count($matches[0]),
                'matched'  => trim((string)$first[0]),
                'offset'   => (int)$first[1],
                'evidence' => self::evidence($text, (int)$first[1]),
            ];
        }

        return $findings;
    }

    /* ── References that can be checked ──────────────────────────────────────── */

    /**
     * Australian legislation an RTO assessment legitimately cites.
     *
     * Deliberately a fixed list rather than a network lookup. Three reasons: a Moodle cron
     * job making outbound requests per submission is fragile and slow; the jurisdictions that
     * matter for VET are a short, stable list; and an unverifiable reference must be reported
     * as unverifiable, which a missing network call cannot distinguish from a fabrication.
     *
     * Keys are lowercase short titles without the year. Values are the years that exist, and
     * the jurisdictions. A citation naming a real Act with the WRONG year is a finding -
     * that is one of the most common ways a fabricated reference presents.
     *
     * Not exhaustive and not meant to be. A reference absent from this list is reported as
     * "not recognised", never as "fabricated", and the report says the list is not complete.
     *
     * @return array Map of lowercase short title => ['years' => int[], 'jurisdiction' => string].
     */
    public static function legislation_registry(): array {
        return [
            // Work health and safety: the model Act and each jurisdiction's enactment.
            'work health and safety act'          => [
                'years' => [2011, 2012, 2020],
                'jurisdiction' => 'Cth/NSW/Qld/SA/Tas/ACT/NT/WA',
            ],
            'work health and safety regulations'  => ['years' => [2011, 2012, 2017, 2022], 'jurisdiction' => 'Cth/states'],
            'occupational health and safety act' => ['years' => [2004], 'jurisdiction' => 'Vic'],
            'occupational health and safety regulations' => ['years' => [2017], 'jurisdiction' => 'Vic'],
            'occupational safety and health act' => ['years' => [1984], 'jurisdiction' => 'WA (repealed 2022)'],

            // Vocational education and training.
            'national vocational education and training regulator act' => ['years' => [2011], 'jurisdiction' => 'Cth'],
            'education and training reform act'  => ['years' => [2006], 'jurisdiction' => 'Vic'],

            // Privacy, records, discrimination, employment.
            'privacy act'                        => ['years' => [1988], 'jurisdiction' => 'Cth'],
            'fair work act'                      => ['years' => [2009], 'jurisdiction' => 'Cth'],
            'disability discrimination act'      => ['years' => [1992], 'jurisdiction' => 'Cth'],
            'sex discrimination act'             => ['years' => [1984], 'jurisdiction' => 'Cth'],
            'racial discrimination act'          => ['years' => [1975], 'jurisdiction' => 'Cth'],
            'age discrimination act'             => ['years' => [2004], 'jurisdiction' => 'Cth'],
            'australian human rights commission act' => ['years' => [1986], 'jurisdiction' => 'Cth'],
            'competition and consumer act'       => ['years' => [2010], 'jurisdiction' => 'Cth'],
            'equal opportunity act'              => ['years' => [1984, 2010], 'jurisdiction' => 'WA/Vic'],

            // Care, health and children.
            'aged care act'                      => ['years' => [1997], 'jurisdiction' => 'Cth'],
            'national disability insurance scheme act' => ['years' => [2013], 'jurisdiction' => 'Cth'],
            'children and young persons (care and protection) act' => ['years' => [1998], 'jurisdiction' => 'NSW'],
            'child wellbeing and safety act'     => ['years' => [2005], 'jurisdiction' => 'Vic'],
            'health practitioner regulation national law' => ['years' => [2009], 'jurisdiction' => 'national'],
            'public health act'                  => ['years' => [2005, 2010, 2016], 'jurisdiction' => 'Qld/NSW/Vic'],

            // Food.
            'food act'                           => ['years' => [1984, 2001, 2003, 2006], 'jurisdiction' => 'Vic/Qld/NSW/WA'],
            'food standards australia new zealand act' => ['years' => [1991], 'jurisdiction' => 'Cth'],

            // Other commonly cited in VET.
            'environment protection act'         => ['years' => [1970, 1993, 2017], 'jurisdiction' => 'Vic/SA'],
            'workers compensation act'           => ['years' => [1987, 1951], 'jurisdiction' => 'NSW/Qld'],
            'workplace injury rehabilitation and compensation act' => ['years' => [2013], 'jurisdiction' => 'Vic'],
            'spam act'                           => ['years' => [2003], 'jurisdiction' => 'Cth'],
            'copyright act'                      => ['years' => [1968], 'jurisdiction' => 'Cth'],
        ];
    }

    /**
     * Extract and check every citation the text makes to a named Act or Regulation.
     *
     * Three kinds of finding come out of this:
     *   - the Act is not in the registry (reported as not recognised, not as fabricated);
     *   - the Act is real but the year is wrong (a strong finding, and a common signature of
     *     a reference that was generated rather than looked up);
     *   - the citation names a section number, which is quoted so a trainer can check it.
     *
     * @param string $text Text as extracted from the submitted file.
     * @return array List of findings.
     */
    public static function legislation_references(string $text): array {
        $registry = self::legislation_registry();
        $findings = [];
        $seen = [];

        /*
         * "<Title> Act|Regulations <year>", with the title limited to words that can appear
         * in one: capitalised words, "and", "of", "the", and parenthesised qualifiers such as
         * "(Care and Protection)". Anchored on the Act/Regulations keyword and the year, so
         * ordinary prose cannot match.
         */
        // One word of a title: a capitalised word, a lowercase connector, or a parenthesised
        // qualifier such as "(Care and Protection)".
        $titleword = '(?:[A-Z][A-Za-z\'-]+|and|of|the|\([A-Za-z\s]+\))';
        $pattern = '/\b(' . $titleword . '(?:\s+' . $titleword . '){0,9})\s+'
            . '(Act|Regulations?|Law)\s+(?:\(\s*[A-Za-z]{2,3}\s*\)\s*)?(\d{4})\b/';

        if (!preg_match_all($pattern, $text, $matches, PREG_SET_ORDER | PREG_OFFSET_CAPTURE)) {
            return $findings;
        }

        foreach ($matches as $match) {
            [$whole, $offset] = $match[0];
            $title = trim(preg_replace('/\s+/', ' ', $match[1][0]));
            $kind  = $match[2][0];
            $year  = (int)$match[3][0];

            /*
             * Strip the words that carried the citation into the sentence.
             *
             * The title pattern has to allow lowercase connectors ("and", "of", "the") so it
             * can match "Work Health and Safety Act" and "Children and Young Persons (Care
             * and Protection) Act". That also lets it swallow the preposition in front:
             * "under Section 19 of the Work Health and Safety Act 2011" captured as "of the
             * Work Health and Safety", which missed the registry and reported a correctly
             * cited Act as unrecognised. A false finding against a student who cited the law
             * properly is the worst failure this class can have, so the leading connectors
             * come off before the lookup. No Act title begins with one.
             */
            $leading = '/^(?:of|the|under|in|to|by|per|with|a|an|and|see|from)\s+/i';
            // Repeated, because a citation can arrive behind more than one of them
            // ("as set out in the ...", "of the ..."). One pass is not enough.
            while (preg_match($leading, $title)) {
                $title = preg_replace($leading, '', $title);
            }
            $title = trim($title);
            if ($title === '') {
                continue;
            }

            // Normalise to the registry's key shape: lowercase, Regulation(s) singularised.
            $key = strtolower($title . ' ' . preg_replace('/^Regulations?$/i', 'Regulations', $kind));
            $key = preg_replace('/\s+/', ' ', $key);

            $dedupe = $key . '|' . $year;
            if (isset($seen[$dedupe])) {
                continue;
            }
            $seen[$dedupe] = true;

            if (!isset($registry[$key])) {
                $findings[] = [
                    'check'    => 'reference_unrecognised',
                    'label'    => 'not in the recognised list',
                    'severity' => self::SEVERITY_NOTABLE,
                    'matched'  => trim($whole),
                    'offset'   => (int)$offset,
                    'evidence' => self::evidence($text, (int)$offset),
                ];
                continue;
            }

            $entry = $registry[$key];
            if (!in_array($year, $entry['years'], true)) {
                $findings[] = [
                    'check'    => 'reference_wrong_year',
                    'label'    => 'real Act, year does not exist',
                    'severity' => self::SEVERITY_STRONG,
                    'matched'  => trim($whole),
                    'expected' => implode(', ', $entry['years']),
                    'jurisdiction' => $entry['jurisdiction'],
                    'offset'   => (int)$offset,
                    'evidence' => self::evidence($text, (int)$offset),
                ];
            }

            if (count($findings) >= self::MAX_PER_CHECK) {
                break;
            }
        }

        return $findings;
    }

    /*
     * REMOVED BEFORE RELEASE: a unit-of-competency code format check.
     *
     * The idea was to flag codes that cannot be real because they are malformed - leaving
     * whether a well-formed code actually EXISTS to training.gov.au, which is out of scope
     * here for the same reasons as a live legislation lookup.
     *
     * It was written, tested, and failed its own test on the first real code it saw. The
     * format was taken to be three to six letters then three or four digits, which rejects
     * SITXFSA005 and SITXFSA006 - seven letters, both entirely valid. Widening the rule to
     * cover the real spread (TLILIC0003, CPCCWHS1001, CHCCCS031, HLTAID011) makes it almost
     * identical to the pattern used to FIND candidates in the first place, so it would
     * approve everything and discriminate nothing.
     *
     * Unit code shapes vary too much across training packages to validate by pattern. The
     * check is not here because a check that flags a real unit code as invalid is worse than
     * no check at all, and a vacuous one that always passes is worse still: it would sit in
     * the report implying something had been verified. Code verification belongs with a
     * training.gov.au lookup, scoped separately.
     */

    /* ── What the file records about itself ──────────────────────────────────── */

    /**
     * Read provenance from a submitted file: what it records about how it was made.
     *
     * CONTEXT SEVERITY, ALWAYS, and the reason is not politeness. A document created from a
     * template, exported from Google Docs, produced on a phone, or typed up from handwritten
     * notes in one sitting all produce the same pattern as one that was pasted. These fields
     * answer "how was this file assembled", which is a useful question, and they do not answer
     * "who wrote the words".
     *
     * Absence of metadata is reported as absence. It is not evidence of anything - plenty of
     * perfectly ordinary pipelines strip it - and it must never read as a clean result.
     *
     * @param string $path Absolute path to a local copy of the submitted file.
     * @param string $filename Original filename, used only to pick the reader.
     * @param int $wordcount Words extracted, so editing time can be put in proportion.
     * @return array ['available' => bool, 'fields' => array, 'findings' => array]
     */
    public static function provenance(string $path, string $filename, int $wordcount = 0): array {
        $extension = strtolower(pathinfo($filename, PATHINFO_EXTENSION));

        if ($extension === 'docx') {
            $fields = self::docx_provenance($path);
        } else if ($extension === 'pdf') {
            $fields = self::pdf_provenance($path);
        } else {
            $fields = [];
        }

        // Findings are computed from the untruncated values - a date must not be cut before
        // it is parsed - then every value is capped before it is stored or displayed.
        $findings = $fields ? self::provenance_findings($fields, $wordcount) : [];

        foreach ($fields as $name => $value) {
            $value = (string)$value;
            if (\core_text::strlen($value) > self::PROVENANCE_FIELD_MAX) {
                $value = \core_text::substr($value, 0, self::PROVENANCE_FIELD_MAX) . '…';
            }
            // A control character in a metadata field has no legitimate purpose and would
            // break the JSON encode on the way into the database.
            $fields[$name] = (string)preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u', '', $value);
        }

        return [
            'available' => !empty($fields),
            'fields'    => $fields,
            'findings'  => $findings,
        ];
    }

    /**
     * Read docProps/app.xml and docProps/core.xml out of a .docx package.
     *
     * @param string $path Absolute path to the .docx.
     * @return array Field name => value, for whichever fields are present.
     */
    protected static function docx_provenance(string $path): array {
        if (!class_exists('ZipArchive')) {
            return [];
        }
        $zip = new \ZipArchive();
        if ($zip->open($path) !== true) {
            return [];
        }
        $app  = (string)$zip->getFromName('docProps/app.xml');
        $core = (string)$zip->getFromName('docProps/core.xml');
        $zip->close();

        $pick = static function (string $xml, string $tag) {
            // Namespace prefix is not fixed across producers, so match on the local name.
            if (preg_match('~<(?:[A-Za-z0-9]+:)?' . preg_quote($tag, '~') . '\b[^>]*>(.*?)</~s', $xml, $m)) {
                $value = trim(html_entity_decode($m[1], ENT_QUOTES | ENT_XML1, 'UTF-8'));
                return $value === '' ? null : $value;
            }
            return null;
        };

        $fields = [
            'editing_minutes' => $pick($app, 'TotalTime'),
            'application'     => $pick($app, 'Application'),
            'app_version'     => $pick($app, 'AppVersion'),
            'declared_words'  => $pick($app, 'Words'),
            'created'         => $pick($core, 'created'),
            'modified'        => $pick($core, 'modified'),
            'revision'        => $pick($core, 'revision'),
            'creator'         => $pick($core, 'creator'),
            'last_modified_by' => $pick($core, 'lastModifiedBy'),
        ];

        return array_filter($fields, static fn($v) => $v !== null);
    }

    /**
     * Read the document information dictionary out of a PDF.
     *
     * Uses pdfinfo when it is available, because PDF metadata is frequently inside a
     * compressed object stream that a regular expression over the raw bytes cannot see. When
     * pdfinfo is absent the raw scan is attempted and will often find nothing, which is
     * reported honestly as no metadata rather than as a clean document.
     *
     * @param string $path Absolute path to the PDF.
     * @return array Field name => value.
     */
    protected static function pdf_provenance(string $path): array {
        $fields = [];

        $tools = extractor::extraction_tools();
        if (!empty($tools['pdftotext'])) {
            // poppler-utils present, so pdfinfo is beside pdftotext.
            $output = [];
            $status = 0;
            @exec('pdfinfo ' . escapeshellarg($path) . ' 2>/dev/null', $output, $status);
            if ($status === 0) {
                foreach ($output as $line) {
                    if (!preg_match('/^([A-Za-z ]+):\s+(.*)$/', $line, $m)) {
                        continue;
                    }
                    $key = strtolower(str_replace(' ', '_', trim($m[1])));
                    if (in_array($key, ['producer', 'creator', 'creationdate', 'moddate', 'pages', 'author'], true)) {
                        $value = trim($m[2]);
                        if ($value !== '') {
                            $fields[$key] = $value;
                        }
                    }
                }
            }
        }

        if (empty($fields)) {
            // Fallback: uncompressed info dictionary, which some producers still emit.
            $head = (string)@file_get_contents($path, false, null, 0, 400000);
            foreach (['Producer' => 'producer', 'Creator' => 'creator'] as $tag => $key) {
                if (preg_match('~/' . $tag . '\s*\(((?:[^()\\\\]|\\\\.){1,200})\)~', $head, $m)) {
                    $fields[$key] = trim($m[1]);
                }
            }
        }

        return $fields;
    }

    /**
     * Turn provenance fields into observations, where any are worth making.
     *
     * @param array $fields Output of docx_provenance() or pdf_provenance().
     * @param int $wordcount Words extracted from the document.
     * @return array List of findings, all at CONTEXT severity.
     */
    protected static function provenance_findings(array $fields, int $wordcount): array {
        $findings = [];

        $add = static function (string $label, string $detail) use (&$findings) {
            $findings[] = [
                'check'    => 'provenance',
                'label'    => $label,
                'severity' => self::SEVERITY_CONTEXT,
                'matched'  => $detail,
                'offset'   => null,
                'evidence' => null,
            ];
        };

        /*
         * Recorded editing time against length, in words per minute.
         *
         * COMPOSITION_WPM_CEILING is set from transcription speed, not composition speed.
         * Sustained composition of considered prose runs somewhere around 15 to 25 words a
         * minute; straight copy-typing from a page runs 40 to 60. Above 60 the words were not
         * being formed in that document, they were arriving in it - by paste, or by import.
         *
         * Deliberately set at the transcription ceiling rather than the composition rate,
         * because a learner who drafted on paper and typed it up is doing nothing wrong and
         * must not be flagged for it. That is also why this stays CONTEXT severity however
         * extreme the figure: a document assembled by paste is a fact about the file, and
         * drafting somewhere else - Google Docs, a phone, a notebook - is an ordinary and
         * legitimate way to work.
         *
         * The first version used 100 words per minute, which let 3 minutes for 285 words pass
         * unremarked. That is 95 words a minute, which nobody composes at.
         */
        if (isset($fields['editing_minutes']) && $wordcount >= self::PROVENANCE_MIN_WORDS) {
            $minutes = (int)$fields['editing_minutes'];
            if ($minutes >= 0 && $minutes < ($wordcount / self::COMPOSITION_WPM_CEILING)) {
                $add(
                    'recorded editing time is short for the length',
                    $minutes . ' minute(s) recorded for ' . $wordcount . ' words'
                );
            }
        }

        // One save, for a whole assessment.
        if (isset($fields['revision']) && (int)$fields['revision'] === 1
                && $wordcount >= self::PROVENANCE_MIN_WORDS) {
            $add('document records a single save', 'revision 1');
        }

        // Created and last modified within a couple of minutes of each other.
        if (isset($fields['created'], $fields['modified'])) {
            $created  = strtotime((string)$fields['created']);
            $modified = strtotime((string)$fields['modified']);
            if ($created && $modified && ($modified - $created) >= 0
                    && ($modified - $created) < 120
                    && $wordcount >= self::PROVENANCE_MIN_WORDS) {
                $add(
                    'whole document lifespan under two minutes',
                    'created and last modified ' . ($modified - $created) . ' seconds apart'
                );
            }
        }

        // Authored by someone other than the account that last saved it.
        if (isset($fields['creator'], $fields['last_modified_by'])
                && $fields['creator'] !== $fields['last_modified_by']) {
            $add(
                'created and last saved by different names',
                $fields['creator'] . ' / ' . $fields['last_modified_by']
            );
        }

        /*
         * PDF printed straight from a browser. Chrome's print-to-PDF writes Skia/PDF as the
         * producer, so a submission with that producer was printed from a web page rather
         * than exported from a word processor. Worth knowing, and no more than that: a
         * student may legitimately have written in a browser-based editor.
         */
        if (isset($fields['producer']) && preg_match('/\bskia\b/i', (string)$fields['producer'])) {
            $add('PDF printed from a browser page', (string)$fields['producer']);
        }

        return $findings;
    }

    /* ── Assembly and reporting ─────────────────────────────────────────────── */

    /**
     * Run every text-based check over one submission.
     *
     * @param string $text Text as extracted from the submitted file.
     * @return array List of findings, strongest first.
     */
    public static function text_findings(string $text): array {
        $findings = array_merge(
            self::assistant_artefacts($text),
            self::markdown_contamination($text),
            self::legislation_references($text)
        );

        return self::sort_findings($findings);
    }

    /**
     * Order findings so the decisive ones are read first.
     *
     * @param array $findings Findings in any order.
     * @return array The same findings, strongest first, then by position in the document.
     */
    public static function sort_findings(array $findings): array {
        $rank = [
            self::SEVERITY_STRONG  => 0,
            self::SEVERITY_NOTABLE => 1,
            self::SEVERITY_CONTEXT => 2,
        ];
        usort($findings, static function ($a, $b) use ($rank) {
            $byseverity = ($rank[$a['severity']] ?? 9) <=> ($rank[$b['severity']] ?? 9);
            if ($byseverity !== 0) {
                return $byseverity;
            }
            return ($a['offset'] ?? PHP_INT_MAX) <=> ($b['offset'] ?? PHP_INT_MAX);
        });

        return $findings;
    }

    /**
     * How many findings of each severity, for the report heading.
     *
     * Deliberately a count and not a score. There is no honest weighting of these against one
     * another without calibration on real student submissions, and a composite number is how
     * the previous version of this plugin came to display a confident badge derived from
     * signals that measured nothing. A trainer reads "two strong findings" correctly; they
     * read "71/100" as a probability it is not.
     *
     * @param array $findings Findings from text_findings() and provenance().
     * @return array ['strong' => int, 'notable' => int, 'context' => int]
     */
    public static function tally(array $findings): array {
        $tally = ['strong' => 0, 'notable' => 0, 'context' => 0];
        foreach ($findings as $finding) {
            $severity = $finding['severity'] ?? self::SEVERITY_CONTEXT;
            if (isset($tally[$severity])) {
                $tally[$severity]++;
            }
        }

        return $tally;
    }

    /**
     * Verification questions a trainer can ask about the learner's own submission.
     *
     * The most defensible authenticity mechanism available, and it does not depend on any
     * detection being right. If a learner can explain what they submitted, the question is
     * settled in their favour; if they cannot, that is a conversation about competence which
     * the trainer is qualified to have and the software is not.
     *
     * Built from the submission's own sentences by template, with no model involved, so the
     * text never leaves the server. The questions are prompts for a human conversation, not
     * an automated assessment.
     *
     * @param string $text Text as extracted from the submitted file.
     * @param int $limit Most questions to return.
     * @return array List of ['question' => string, 'basis' => string].
     */
    public static function verification_questions(string $text, int $limit = 4): array {
        $questions = [];

        // 1. Technical or regulatory terms the learner used, to explain in their own words.
        $terms = [];
        $phrases = [
            'reasonably practicable', 'duty of care', 'dignity of risk', 'hierarchy of control',
            'administrative control', 'engineering control', 'personal protective equipment',
            'temperature danger zone', 'cross contamination', 'duty holder', 'notifiable incident',
            'risk assessment', 'hazard identification', 'informed consent', 'mandatory reporting',
            'person conducting a business or undertaking', 'safe work method statement',
            'continuous improvement', 'scope of practice', 'confidentiality', 'open disclosure',
        ];
        foreach ($phrases as $phrase) {
            if (stripos($text, $phrase) !== false) {
                $terms[] = $phrase;
            }
        }
        foreach (array_slice($terms, 0, 2) as $term) {
            $questions[] = [
                'question' => 'You used the term "' . $term . '". Can you explain what that means '
                    . 'in your own words, and give an example from your own workplace?',
                'basis'    => 'term used in the submission',
            ];
        }

        // 2. Any citation made, so the learner can say where they found it.
        foreach (array_slice(self::legislation_references($text), 0, 1) as $reference) {
            $questions[] = [
                'question' => 'You referred to ' . $reference['matched'] . '. Where did you find '
                    . 'that requirement, and what does it ask an employer to do?',
                'basis'    => 'reference cited in the submission',
            ];
        }
        if (preg_match_all('/\b(?:Act|Regulations?|Standard|Code of Practice)\s+\d{4}\b/', $text, $m)
                && empty($questions[count($questions) - 1]['basis'] ?? null)) {
            $questions[] = [
                'question' => 'Which source did you use for the legal requirement you mentioned?',
                'basis'    => 'legal requirement referred to',
            ];
        }

        /*
         * 3. The longest sentence in the submission, read back. A learner explaining their own
         * reasoning manages this easily; it is specifically the sentences a learner did not
         * write that are hard to unpack on the spot.
         */
        $sentences = preg_split('/(?<=[.!?])\s+/u', trim(preg_replace('/\s+/u', ' ', $text)), -1, PREG_SPLIT_NO_EMPTY);
        $longest = '';
        foreach ((array)$sentences as $sentence) {
            $sentence = trim($sentence);
            $words = str_word_count($sentence);
            if ($words < 18 || $words > 60) {
                continue;
            }
            /*
             * Only the student's own account, never the assessment template.
             *
             * The first version of this took the longest sentence in the extracted text, which
             * on a real submission is the cover sheet: the header has no sentence punctuation,
             * so the RTO code, the unit title, the student's name and the instructions all
             * parse as one enormous sentence, and the trainer was handed "You wrote:
             * 'ASSESSMENT COVER SHEET Registered Training Organisation code 41234...' - can you
             * talk me through what you meant by that?" Asking a learner to explain their own
             * cover sheet would discredit the whole panel in one line.
             *
             * A first-person pronoun is the filter. These questions ask the learner to account
             * for their own narrative, which is exactly the part of the submission the template
             * did not supply. A submission with no first-person writing simply falls through to
             * the general question below rather than reaching for boilerplate.
             */
            if (!preg_match('/\b(?:I|I\'?m|I\'?ve|my|we|we\'?re|our|me|us)\b/i', $sentence)) {
                continue;
            }
            // Headings and form fields, which survive extraction as runs of capitals.
            if (preg_match('/\b[A-Z]{3,}\b/', $sentence)) {
                continue;
            }
            // Template language, in case a declaration is written in the first person -
            // which it is: "I declare that this assessment is my own work".
            if (preg_match('/\b(?:declare|declaration|assessment task|cover sheet|student id|'
                    . 'reasonably adjust|registered training organisation|plagiarism and cheating|'
                    . 'not yet satisfactory|instructions to the student)\b/i', $sentence)) {
                continue;
            }
            if (strlen($sentence) > strlen($longest)) {
                $longest = $sentence;
            }
        }
        if ($longest !== '') {
            $questions[] = [
                'question' => 'You wrote: "' . $longest . '" Can you talk me through what you meant '
                    . 'by that, and why it matters on the job?',
                'basis'    => 'sentence taken from the submission',
            ];
        }

        // 4. A fallback that always applies, so the trainer is never handed an empty list.
        $questions[] = [
            'question' => 'Tell me how you went about this assessment - what you read, what you '
                . 'drafted first, and anything or anyone that helped you.',
            'basis'    => 'general',
        ];

        return array_slice($questions, 0, max(1, $limit));
    }

    /**
     * Quote the text surrounding a finding, so the trainer sees it in context.
     *
     * @param string $text The full extracted text.
     * @param int $offset Byte offset of the match.
     * @return string A short excerpt, ellipsised, with whitespace collapsed.
     */
    protected static function evidence(string $text, int $offset): string {
        /*
         * BYTE offsets, cut with byte functions.
         *
         * preg_match_all() with PREG_OFFSET_CAPTURE returns byte offsets, with or without the
         * /u modifier. This used core_text::substr(), which is character-based, so the window
         * was taken from a position that drifted by one position for every multi-byte
         * character earlier in the document. Measured: 35 bytes of drift still landed inside
         * the window and looked fine; at 140 bytes the excerpt came out EMPTY, and beyond that
         * it was text from an unrelated part of the submission.
         *
         * That is 140 bytes, not 140 characters - about 45 accented letters, or a couple of
         * dozen uses of °C. A learner called Zoë describing a café fridge reaches it inside a
         * paragraph. The panel's whole claim is that the evidence is quoted so it can be
         * checked, so quoting the wrong passage, or nothing, is worse than having no panel.
         */
        $before = (int)floor(self::EVIDENCE_CHARS / 3);
        $start  = max(0, $offset - $before);
        $excerpt = (string)substr($text, $start, self::EVIDENCE_CHARS);

        /*
         * Either cut can land inside a multi-byte sequence. Drop the orphaned continuation
         * bytes at the front, then shorten from the end until what remains is valid UTF-8 -
         * at most three bytes, since that is the longest incomplete tail possible. Storing
         * invalid UTF-8 would be rejected by MySQL under utf8mb4 (the same class of failure
         * as FIX-DG-MB-TRUNCATE) and would corrupt the JSON encode on the way in.
         */
        $excerpt = (string)preg_replace('/^[\x80-\xBF]+/', '', $excerpt);
        for ($trim = 0; $trim < 4 && $excerpt !== '' && !mb_check_encoding($excerpt, 'UTF-8'); $trim++) {
            $excerpt = (string)substr($excerpt, 0, -1);
        }

        /*
         * Still invalid means the extraction itself carries bad bytes, not that the window was
         * cut badly - a damaged PDF, or a .docx written by something that mislabelled its
         * encoding. Keep the readable part rather than discarding the excerpt: dropping it
         * leaves the trainer looking at a finding with no context at all, which is the same
         * failure the byte-offset bug caused. mb_convert_encoding() from UTF-8 to UTF-8 removes
         * the invalid sequences and leaves the rest intact.
         */
        if (!mb_check_encoding($excerpt, 'UTF-8')) {
            $excerpt = (string)mb_convert_encoding($excerpt, 'UTF-8', 'UTF-8');
            if (!mb_check_encoding($excerpt, 'UTF-8')) {
                return '';
            }
        }

        $excerpt = trim((string)preg_replace('/\s+/u', ' ', $excerpt));
        if ($excerpt === '') {
            return '';
        }

        return ($start > 0 ? '…' : '') . $excerpt . '…';
    }
}
